In [1]:
Q1

from numpy import *
matA=matrix(input("Enter the values for matrixA in string format "))
matB=matrix(input("Enter the values for matrixB in string format "))
print("Addition of both matrices is ")
print(matA+matB)

Enter the values for matrixA in string format 1 2 3; 4 5 6
Enter the values for matrixB in string format 3 2 1; 6 5 4
Addition of both matrices is 
[[ 4  4  4]
 [10 10 10]]


In [2]:
Q2

from numpy import *
matA=matrix(input("Enter the values for matrixA in string format "))
matB=matrix(input("Enter the values for matrixB in string format "))
print("Multiplication of both matrices is ")
print(matA*matB)

Enter the values for matrixA in string format 1 2; 2 1 
Enter the values for matrixB in string format 2 1; 1 2
Multiplication of both matrices is 
[[4 5]
 [5 4]]


In [3]:
Q3

from numpy import *
matA=matrix(input("Enter the values for matrixA in string format "))
print("Transpose of the matrix is ")
print(matA.transpose())

Enter the values for matrixA in string format 1 3; 4 5
Transpose of the matrix is 
[[1 4]
 [3 5]]


In [8]:
Q4

words=[x for x in input("Enter the words ").split(" ")]
print("The sorted words are:")
words.sort()
for word in words:
    print(word,end=" ")

Enter the words Ram Raju rani
The sorted words are:
Raju Ram rani 

In [9]:
Q5

import re
test_str = input("Enter a string :")
print("The original string is : ",test_str)
res = re.sub(r'[^\w\s]', '', test_str)
print("The string after punctuation filter : ",res)

Enter a string :My username is Rahul123, Do you know me? That's great!
The original string is :  My username is Rahul123, Do you know me? That's great!
The string after punctuation filter :  My username is Rahul123 Do you know me Thats great
